on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
      checks: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: the-pr-agent/pr-agent@main
        env:
          DEEPSEEK__KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # 直接指定官方模型
          CONFIG__MODEL: "deepseek/deepseek-chat"
          CONFIG__FALLBACK_MODELS: "['deepseek/deepseek-chat']"

          PR_DESCRIPTION__RESPONSE_LANGUAGE: "zh-CN"
          PR_REVIEWER__RESPONSE_LANGUAGE: "zh-CN"
